# How links connect together
kinematics:
  joint0:
    x: 0
    y: 0
    z: 0.0775
    roll: 0
    pitch: 0
    yaw: 0
  joint1:
    x: 0
    y: -0.109
    z: 0.222
    roll: 1.570796327
    pitch: 0
    yaw: 0
  joint2:
    x: 0
    y: 0.45
    z: -0.0305
    roll: 0
    pitch: 0
    yaw: 3.1415926536
  joint3:
    x: 0
    y: -0.267
    z: -0.075
    roll: -1.570796327
    pitch: 0
    yaw: 3.1415926536
  joint4:
    x: 0
    y: -0.114
    z: 0.0835
    roll: 1.570796327
    pitch: 0
    yaw: 0
  joint5:
    x: 0
    y: 0.052
    z: 0.085
    roll: -1.570796327
    pitch: 0
    yaw: 0
  tcp:
    x: 0.0
    y: 0.0
    z: 0.0505
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
