mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/visual/Indy7_v2_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy7_v2/collision/Indy7_v2_6.stl
