# How links connect together
kinematics:
  joint0:
    x: 0
    y: 0
    z: 0.0785
    roll: 0
    pitch: 0
    yaw: 0
  joint1:
    x: 0
    y: -0.1103
    z: 0.2215
    roll: 1.570796327
    pitch: 0
    yaw: 0
  joint2:
    x: 0
    y: 0.3605
    z: 0.0832
    roll: -1.570796327
    pitch: 0
    yaw: 0
  joint3:
    x: 0
    y: 0.1163
    z: 0.0895
    roll: -1.570796327
    pitch: 0
    yaw: 3.1415926536
  joint4:
    x: 0
    y: -0.2655
    z: -0.0737
    roll: -1.570796327
    pitch: 0
    yaw: 3.1415926536
  joint5:
    x: 0
    y: -0.1153
    z: 0.0845
    roll: 1.570796327
    pitch: 0
    yaw: 0
  joint6:
    x: 0
    y: 0.052
    z: 0.0837
    roll: -1.570796327
    pitch: 0
    yaw: 0
  tcp:
    x: 0.0
    y: 0.0
    z: 0.0515
    roll: 0.0
    pitch: 0.0
    yaw: 0.0