joint_limits:
  joint0:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 431.97
    max_velocity: !degrees 150.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint1:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 431.97
    max_velocity: !degrees 150.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint2:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 197.23
    max_velocity: !degrees 150.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint3:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 197.23
    max_velocity: !degrees 150.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint4:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 79.79
    max_velocity: !degrees 180.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint5:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 79.79
    max_velocity: !degrees 180.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0
  joint6:
    has_effort_limits: true
    has_velocity_limits: true
    has_position_limits: true
    has_acceleration_limits: false
    max_effort: 79.79
    max_velocity: !degrees 180.0
    max_position: !degrees  175.0
    min_position: !degrees -175.0