mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_6.stl
  link7:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_7.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_7.stl
  link7_eye:
    visual:
      mesh:
        package: indy_description
        path: meshes/indyrp2/visual/IndyRP2_eye_7.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indyrp2/collision/IndyRP2_eye_7.stl
        