mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri7c/visual/Nuri7c_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri7c/collision/Nuri7c_6.stl
