mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/icon3/visual/ICoN3_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/icon3/collision/ICoN3_6.stl
