mesh_files:
  link0:
    visual_origin:
      xyz: "0 0 0"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_0.stl
  link1:
    visual_origin:
      xyz: "0 0 -0.082"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_1.stl
  link2:
    visual_origin:
      xyz: "0 0.136 -0.350"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_2.stl
  link3:
    visual_origin:
      xyz: "0 0.116 -1.000"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_3.stl
  link4:
    visual_origin:
      xyz: "0 0.009 -1.187"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_4.stl
  link5:
    visual_origin:
      xyz: "0 0.116 -1.550"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_5.stl
  link6:
    visual_origin:
      xyz: "0 0.218 -1.636"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_6.stl
  link6_eye:
    visual_origin:
      xyz: "0 0 0"
      rpy: "0 0 0"
    visual:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/visual/Indy12_v3_eye_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/indy12_v3/collision/Indy12_v3_eye_6.stl
