mesh_files:
  link0:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_0.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_0.stl
  link1:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_1.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_1.stl
  link2:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_2.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_2.stl
  link3:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_3.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_3.stl
  link4:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_4.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_4.stl
  link5:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_5.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_5.stl
  link6:
    visual:
      mesh:
        package: indy_description
        path: meshes/nuri30/visual/Nuri30_6.stl
    collision:
      mesh:
        package: indy_description
        path: meshes/nuri30/collision/Nuri30_6.stl
